---
port: /dev/ttyACM0

devices:
  - type: mi_thermometer
    mac_address: a4:c1:38:8f:ed:57
    tags: 
      - { name: location, value: bedroom }
  - type: mi_thermometer
    mac_address: a4:c1:38:d4:89:e3
    tags: 
      - { name: location, value: bathroom }
  - type: mi_scale
    mac_address: 5c:ca:d3:ed:7f:27
